# Generated by Django 5.2.11 on 2026-03-20 22:46

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('estagio_evolucao', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('valor_base_geracao', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PerfilTreinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_moedas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_treinador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('slots_max', models.PositiveIntegerField(default=30)),
                ('perfil_treinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='website.perfiltreinador')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonInstancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(max_length=80)),
                ('data_nascimento', models.DateTimeField(default=django.utils.timezone.now)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemons', to='website.box')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instancias', to='website.especie')),
            ],
        ),
        migrations.CreateModel(
            name='Ovo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=12)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ovos', to='website.especie')),
                ('perfil_treinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ovos', to='website.perfiltreinador')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ovos', to='website.tipopokemon')),
            ],
        ),
        migrations.AddField(
            model_name='especie',
            name='tipos',
            field=models.ManyToManyField(related_name='especies', to='website.tipopokemon'),
        ),
    ]
