# Generated by Django 5.2.11 on 2026-03-20 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemoninstancia',
            name='box',
        ),
        migrations.RemoveField(
            model_name='especie',
            name='tipos',
        ),
        migrations.RemoveField(
            model_name='pokemoninstancia',
            name='especie',
        ),
        migrations.RemoveField(
            model_name='ovo',
            name='especie',
        ),
        migrations.RemoveField(
            model_name='ovo',
            name='perfil_treinador',
        ),
        migrations.RemoveField(
            model_name='ovo',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='perfiltreinador',
            name='user',
        ),
        migrations.DeleteModel(
            name='Box',
        ),
        migrations.DeleteModel(
            name='PokemonInstancia',
        ),
        migrations.DeleteModel(
            name='Especie',
        ),
        migrations.DeleteModel(
            name='Ovo',
        ),
        migrations.DeleteModel(
            name='TipoPokemon',
        ),
        migrations.DeleteModel(
            name='PerfilTreinador',
        ),
    ]
