# Generated by Django 5.2.11 on 2026-06-12 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_sync_schema_and_convert_ovo_species'),
        ('pokemon', '0003_migration_ovoinventario'),
    ]

    operations = [
    ]
