# Generated by Django 5.2.11 on 2026-06-26 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_merge_20260612_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemoninstancia',
            name='box_position',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
