# Generated by Django 5.2.11 on 2026-08-20 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0005_add_box_position_to_pokemoninstancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemoninstancia',
            name='is_active_team',
            field=models.BooleanField(default=False),
        ),
    ]
