# Generated by Django 5.2.11 on 2026-08-20 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0006_pokemoninstancia_is_active_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='especie',
            name='sprite_url',
            field=models.URLField(blank=True, default='', max_length=300),
        ),
    ]
